export const ADMIN_CREATE_ITEM_SUCCESS = "ADMIN_CREATE_ITEM_SUCCESS";
export const ADMIN_CREATE_ITEM_FAILED = "ADMIN_CREATE_ITEM_FAILED";
export const ADMIN_GET_ITEMS_SUCCESS = "ADMIN_GET_ITEMS_SUCCESS";
export const ADMIN_GET_ITEMS_FAILED = "ADMIN_GET_ITEMS_FAILED";
export const RESET_ITEM_CREATE_RESPONSE_MESSAGE = "RESET_ITEM_CREATE_RESPONSE_MESSAGE";
export const ADMIN_UPDATE_ITEM_SUCCESS = "ADMIN_UPDATE_ITEM_SUCCESS";
export const ADMIN_UPDATE_ITEM_FAILED = "ADMIN_UPDATE_ITEM_FAILED";

export const ADMIN_ITEM_INPUT_CHANGE = "ADMIN_ITEM_INPUT_CHANGE";
export const ADMIN_ITEM_ATTRIBUTE_CHANGE = "ADMIN_ITEM_ATTRIBUTE_CHANGE";
export const ADMIN_ITEM_ADD_ATTRIBUTE = "ADMIN_ITEM_ADD_ATTRIBUTE"; 
export const ADMIN_ITEM_REMOVE_ATTRIBUTE = "ADMIN_ITEM_REMOVE_ATTRIBUTE"; 
export const ADMIN_ITEM_EDIT_CANCEL = "ADMIN_ITEM_EDIT_CANCEL"; 