export const ADMIN_CREATE_ITEM_SUCCESS = "ADMIN_CREATE_ITEM_SUCCESS";
export const ADMIN_CREATE_ITEM_FAILED = "ADMIN_CREATE_ITEM_FAILED";
export const ADMIN_GET_ITEMS_SUCCESS = "ADMIN_GET_ITEMS_SUCCESS";
export const ADMIN_GET_ITEMS_FAILED = "ADMIN_GET_ITEMS_FAILED";
export const RESET_ADMIN_ITEM_CREATE_RESPONSE_MESSAGE = "RESET_ITEM_CREATE_RESPONSE_MESSAGE";
export const ADMIN_UPDATE_ITEM_SUCCESS = "ADMIN_UPDATE_ITEM_SUCCESS";
export const RESET_ADMIN_ITEM_UPDATE_RESPONSE_MESSAGE = "RESET_ADMIN_ITEM_UPDATE_RESPONSE_MESSAGE";
export const ADMIN_UPDATE_ITEM_FAILED = "ADMIN_UPDATE_ITEM_FAILED";
export const ADMIN_ITEM_INPUT_CHANGE = "ADMIN_ITEM_INPUT_CHANGE";
export const ADMIN_ITEM_ATTRIBUTE_CHANGE = "ADMIN_ITEM_ATTRIBUTE_CHANGE";
export const ADMIN_ITEM_ADD_ATTRIBUTE = "ADMIN_ITEM_ADD_ATTRIBUTE"; 
export const ADMIN_ITEM_REMOVE_ATTRIBUTE = "ADMIN_ITEM_REMOVE_ATTRIBUTE"; 
export const ADMIN_ITEM_EDIT_CANCEL = "ADMIN_ITEM_EDIT_CANCEL"; 

export const ADMIN_CREATE_EVENT_SUCCESS = "ADMIN_CREATE_EVENT_SUCCESS";
export const ADMIN_CREATE_EVENT_FAILED = "ADMIN_CREATE_EVENT_FAILED";
export const ADMIN_GET_EVENTS_SUCCESS = "ADMIN_GET_EVENTS_SUCCESS";
export const ADMIN_GET_EVENTS_FAILED = "ADMIN_GET_EVENTS_FAILED";
export const ADMIN_GET_ACTIVE_EVENTS_SUCCESS = "ADMIN_GET_ACTIVE_EVENTS_SUCCESS";
export const ADMIN_GET_ACTIVE_EVENTS_FAILED = "ADMIN_GET_ACTIVE_EVENTS_FAILED";
export const RESET_ADMIN_EVENT_CREATE_RESPONSE_MESSAGE = "RESET_EVENT_CREATE_RESPONSE_MESSAGE";
export const ADMIN_UPDATE_EVENT_SUCCESS = "ADMIN_UPDATE_EVENT_SUCCESS";
export const ADMIN_UPDATE_EVENT_FAILED = "ADMIN_UPDATE_EVENT_FAILED";
export const RESET_ADMIN_EVENT_UPDATE_RESPONSE_MESSAGE = "RESET_ADMIN_EVENT_UPDATE_RESPONSE_MESSAGE";
export const ADMIN_EVENT_INPUT_CHANGE = "ADMIN_EVENT_INPUT_CHANGE";
export const ADMIN_EVENT_DATE_CHANGE = "ADMIN_EVENT_DATE_CHANGE";
export const ADMIN_EVENT_EDIT_CANCEL = "ADMIN_EVENT_EDIT_CANCEL"; 

export const STUDENT_CREATE_EVENT_SUCCESS = "STUDENT_CREATE_EVENT_SUCCESS";
export const STUDENT_CREATE_EVENT_FAILED = "STUDENT_CREATE_EVENT_FAILED";
export const STUDENT_GET_EVENTS_SUCCESS = "STUDENT_GET_EVENTS_SUCCESS";
export const STUDENT_GET_EVENTS_FAILED = "STUDENT_GET_EVENTS_FAILED";
export const RESET_STUDENT_EVENT_CREATE_RESPONSE_MESSAGE = "RESET_STUDENT_EVENT_CREATE_RESPONSE_MESSAGE";
export const STUDENT_UPDATE_EVENT_SUCCESS = "STUDENT_UPDATE_EVENT_SUCCESS";
export const STUDENT_UPDATE_EVENT_FAILED = "STUDENT_UPDATE_EVENT_FAILED";
export const RESET_STUDENT_EVENT_UPDATE_RESPONSE_MESSAGE = "RESET_STUDENT_EVENT_UPDATE_RESPONSE_MESSAGE";
export const STUDENT_EVENT_INPUT_CHANGE = "STUDENT_EVENT_INPUT_CHANGE";
export const STUDENT_EVENT_EDIT_CANCEL = "STUDENT_EVENT_EDIT_CANCEL";
export const STUDENT_EVENT_ADD_COMMENT_SUCCESS = "STUDENT_EVENT_ADD_COMMENT_SUCCESS";
export const STUDENT_EVENT_ADD_COMMENT_FAILED = "STUDENT_EVENT_ADD_COMMENT_FAILED";
export const RESET_STUDENT_EVENT_ADD_COMMENT_RESPONSE = "RESET_STUDENT_EVENT_ADD_COMMENT_RESPONSE";

export const REQUESTS_GET_ALL_EVENTS_SUCCESS = "REQUESTS_GET_ALL_EVENTS_SUCCESS";
export const REQUESTS_GET_ALL_EVENTS_FAILED = "REQUESTS_GET_ALL_EVENTS_FAILED";
export const REQUESTS_UPDATE_EVENT_STATUS_SUCCESS = "REQUESTS_UPDATE_EVENT_STATUS_SUCCESS";
export const REQUESTS_UPDATE_EVENT_STATUS_FAILED = "REQUESTS_UPDATE_EVENT_STATUS_FAILED";
export const REQUESTS_EVENT_ADD_COMMENT_SUCCESS = "REQUESTS_EVENT_ADD_COMMENT_SUCCESS";
export const REQUESTS_EVENT_ADD_COMMENT_FAILED = "REQUESTS_EVENT_ADD_COMMENT_FAILED";
export const RESET_REQUESTS_EVENT_ADD_COMMENT_RESPONSE = "RESET_REQUESTS_EVENT_ADD_COMMENT_RESPONSE";

export const STUDENT_GET_ORDERS_SUCCESS = "STUDENT_GET_ORDERS_SUCCESS";
export const STUDENT_GET_ORDERS_FAILED = "STUDENT_GET_ORDERS_FAILED";
export const STUDENT_ORDER_ADD_COMMENT_SUCCESS = "STUDENT_ORDER_ADD_COMMENT_SUCCESS";
export const STUDENT_ORDER_ADD_COMMENT_FAILED = "STUDENT_ORDER_ADD_COMMENT_FAILED";
export const RESET_STUDENT_ORDER_ADD_COMMENT_RESPONSE = "RESET_STUDENT_EVENT_ADD_COMMENT_RESPONSE";

export const REQUESTS_GET_ALL_ORDERS_SUCCESS = "REQUESTS_GET_ALL_ORDERS_SUCCESS";
export const REQUESTS_GET_ALL_ORDERS_FAILED = "REQUESTS_GET_ALL_ORDERS_FAILED";
export const REQUESTS_UPDATE_ORDER_STATUS_SUCCESS = "REQUESTS_UPDATE_ORDER_STATUS_SUCCESS";
export const REQUESTS_UPDATE_ORDER_STATUS_FAILED = "REQUESTS_UPDATE_ORDER_STATUS_FAILED";
export const REQUESTS_ORDER_ADD_COMMENT_SUCCESS = "REQUESTS_ORDER_ADD_COMMENT_SUCCESS";
export const REQUESTS_ORDER_ADD_COMMENT_FAILED = "REQUESTS_ORDER_ADD_COMMENT_FAILED";
export const RESET_REQUESTS_ORDER_ADD_COMMENT_RESPONSE = "RESET_REQUESTS_ORDER_ADD_COMMENT_RESPONSE";

export const STUDENT_DASHBOARD_GET_POINTS_SUCCESS = "STUDENT_DASHBOARD_GET_POINTS_SUCCESS";
export const STUDENT_DASHBOARD_GET_POINTS_FAILED = "STUDENT_DASHBOARD_GET_POINTS_FAILED";
export const STUDENT_DASHBOARD_GET_EVENTS_SUCCESS = "STUDENT_DASHBOARD_GET_EVENTS_SUCCESS";
export const STUDENT_DASHBOARD_GET_EVENTS_FAILED = "STUDENT_DASHBOARD_GET_EVENTS_FAILED";
export const STUDENT_DASHBOARD_GET_APPROVED_EVENTS_SUCCESS = "STUDENT_DASHBOARD_GET_APPROVED_EVENTS_SUCCESS";
export const STUDENT_DASHBOARD_GET_APPROVED_EVENTS_FAILED = "STUDENT_DASHBOARD_GET_APPROVED_EVENTS_FAILED";
export const STUDENT_DASHBOARD_GET_ORDERS_SUCCESS = "STUDENT_DASHBOARD_GET_ORDERS_SUCCESS";
export const STUDENT_DASHBOARD_GET_ORDERS_FAILED = "STUDENT_DASHBOARD_GET_ORDERS_FAILED";
export const STUDENT_DASHBOARD_GET_DELIVERED_ORDERS_SUCCESS = "STUDENT_DASHBOARD_GET_DELIVERED_ORDERS_SUCCESS";
export const STUDENT_DASHBOARD_GET_DELIVERED_ORDERS_FAILED = "STUDENT_DASHBOARD_GET_DELIVERED_ORDERS_FAILED";
export const STUDENT_DASHBOARD_GET_SUGGESTED_EVENTS_SUCCESS = "STUDENT_DASHBOARD_GET_SUGGESTED_EVENTS_SUCCESS";
export const STUDENT_DASHBOARD_GET_SUGGESTED_EVENTS_FAILED = "STUDENT_DASHBOARD_GET_SUGGESTED_EVENTS_FAILED";
export const STUDENT_DASHBOARD_GET_APPROVED_SUGGESTED_EVENTS_SUCCESS = "STUDENT_DASHBOARD_GET_APPROVED_SUGGESTED_EVENTS_SUCCESS";
export const STUDENT_DASHBOARD_GET_APPROVED_SUGGESTED_EVENTS_FAILED = "STUDENT_DASHBOARD_GET_APPROVED_SUGGESTED_EVENTS_FAILED";

export const ADMIN_DASHBOARD_GET_PENDING_APPROVAL_EVENTS_SUCCESS = "ADMIN_DASHBOARD_GET_PENDING_APPROVAL_EVENTS_SUCCESS";
export const ADMIN_DASHBOARD_GET_PENDING_APPROVAL_EVENTS_FAILED = "ADMIN_DASHBOARD_GET_PENDING_APPROVAL_EVENTS_FAILED";
export const ADMIN_DASHBOARD_GET_SUBMITTED_ORDERS_SUCCESS = "ADMIN_DASHBOARD_GET_SUBMITTED_ORDERS_SUCCESS";
export const ADMIN_DASHBOARD_GET_SUBMITTED_ORDERS_FAILED = "ADMIN_DASHBOARD_GET_SUBMITTED_ORDERS_FAILED";
export const ADMIN_DASHBOARD_GET_PENDING_APPROVAL_SUGGESTED_EVENTS_SUCCESS = "ADMIN_DASHBOARD_GET_PENDING_APPROVAL_SUGGESTED_EVENTS_SUCCESS";
export const ADMIN_DASHBOARD_GET_PENDING_APPROVAL_SUGGESTED_EVENTS_FAILED = "ADMIN_DASHBOARD_GET_PENDING_APPROVAL_SUGGESTED_EVENTS_FAILED";

export const STUDENT_CREATE_SUGGESTED_EVENT_SUCCESS = "STUDENT_CREATE_SUGGESTED_EVENT_SUCCESS";
export const STUDENT_CREATE_SUGGESTED_EVENT_FAILED = "STUDENT_CREATE_SUGGESTED_EVENT_FAILED";
export const STUDENT_GET_SUGGESTED_EVENTS_SUCCESS = "STUDENT_GET_SUGGESTED_EVENTS_SUCCESS";
export const STUDENT_GET_SUGGESTED_EVENTS_FAILED = "STUDENT_GET_SUGGESTED_EVENTS_FAILED";
export const RESET_STUDENT_SUGGESTED_EVENT_CREATE_RESPONSE_MESSAGE = "RESET_STUDENT_SUGGESTED_EVENT_CREATE_RESPONSE_MESSAGE";
export const STUDENT_SUGGESTED_EVENT_ADD_COMMENT_SUCCESS = "STUDENT_SUGGESTED_EVENT_ADD_COMMENT_SUCCESS";
export const STUDENT_SUGGESTED_EVENT_ADD_COMMENT_FAILED = "STUDENT_SUGGESTED_EVENT_ADD_COMMENT_FAILED";
export const RESET_STUDENT_SUGGESTED_EVENT_ADD_COMMENT_RESPONSE = "RESET_STUDENT_SUGGESTED_EVENT_ADD_COMMENT_RESPONSE";

export const REQUESTS_GET_ALL_SUGGESTED_EVENTS_SUCCESS = "REQUESTS_GET_ALL_SUGGESTED_EVENTS_SUCCESS";
export const REQUESTS_GET_ALL_SUGGESTED_EVENTS_FAILED = "REQUESTS_GET_ALL_SUGGESTED_EVENTS_FAILED";
export const REQUESTS_UPDATE_SUGGESTED_EVENT_STATUS_SUCCESS = "REQUESTS_UPDATE_SUGGESTED_EVENT_STATUS_SUCCESS";
export const REQUESTS_UPDATE_SUGGESTED_EVENT_STATUS_FAILED = "REQUESTS_UPDATE_SUGGESTED_EVENT_STATUS_FAILED";
export const REQUESTS_SUGGESTED_EVENT_ADD_COMMENT_SUCCESS = "REQUESTS_SUGGESTED_EVENT_ADD_COMMENT_SUCCESS";
export const REQUESTS_SUGGESTED_EVENT_ADD_COMMENT_FAILED = "REQUESTS_SUGGESTED_EVENT_ADD_COMMENT_FAILED";
export const RESET_REQUESTS_SUGGESTED_EVENT_ADD_COMMENT_RESPONSE = "RESET_REQUESTS_SUGGESTED_EVENT_ADD_COMMENT_RESPONSE";

export const REQUESTS_GET_ALL_STUDENTS_SUCCESS = "REQUESTS_GET_ALL_STUDENTS_SUCCESS";
export const REQUESTS_GET_ALL_STUDENTS_FAILED = "REQUESTS_GET_ALL_STUDENTS_FAILED";
export const REQUESTS_STUDENT_EDIT_CANCEL = "REQUESTS_STUDENT_EDIT_CANCEL";
export const REQUESTS_UPDATE_STUDENT_STATUS_SUCCESS = "REQUESTS_UPDATE_LOGIN_STATUS_SUCCESS";
export const REQUESTS_UPDATE_STUDENT_STATUS_FAILED = "REQUESTS_UPDATE_LOGIN_STATUS_FAILED";
export const REQUESTS_UPDATE_STUDENT_POINTS_SUCCESS = "REQUESTS_UPDATE_STUDENT_POINTS_SUCCESS";
export const REQUESTS_UPDATE_STUDENT_POINTS_FAILED = "REQUESTS_UPDATE_STUDENT_POINTS_FAILED";
export const RESET_REQUESTS_STUDENT_POINTS_UPDATE_RESPONSE = "RESET_REQUESTS_STUDENT_POINTS_UPDATE_RESPONSE";

export const MANAGER_CREATE_ADMIN_SUCCESS = "MANAGER_CREATE_ADMIN_SUCCESS";
export const MANAGER_CREATE_ADMIN_FAILED = "MANAGER_CREATE_ADMIN_FAILED";
export const RESET_MANAGER_CREATE_ADMIN_RESPONSE_MESSAGE = "RESET_MANAGER_CREATE_ADMIN_RESPONSE_MESSAGE";
export const MANAGER_GET_ALL_ADMINS_SUCCESS = "MANAGER_GET_ALL_ADMINS_SUCCESS";
export const MANAGER_GET_ALL_ADMINS_FAILED = "MANAGER_GET_ALL_ADMINS_FAILED";
export const MANAGER_UPDATE_ADMIN_SUCCESS = "MANAGER_UPDATE_ADMIN_SUCCESS";
export const MANAGER_UPDATE_ADMIN_FAILED = "MANAGER_UPDATE_ADMIN_FAILED";
export const RESET_MANAGER_UPDATE_ADMIN_RESPONSE_MESSAGE = "RESET_MANAGER_UPDATE_ADMIN_RESPONSE_MESSAGE";

export const STUDENT_PROFILE_GET_SUCCESS = "STUDENT_PROFILE_GET_SUCCESS";
export const STUDENT_PROFILE_GET_FAILED = "STUDENT_PROFILE_GET_SUCCESS";
export const STUDENT_PROFILE_SELECT_CHANGE = "STUDENT_PROFILE_SELECT_CHANGE";
export const STUDENT_PROFILE_EDIT_CANCEL = "STUDENT_PROFILE_EDIT_CANCEL";
export const STUDENT_PROFILE_UPDATE_SUCCESS = "STUDENT_PROFILE_UPDATE_SUCCESS";
export const STUDENT_PROFILE_UPDATE_FAILED = "STUDENT_PROFILE_UPDATE_FAILED";